blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'',include('blogapp.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    
    url(r'', include('comments.urls')),
   ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/blogapp/urls.py
from django.conf.urls import url
from . import views
app_name = 'blogapp'
urlpatterns = [
	url(r'^$',views.IndexView.as_view(),name='index'),
	url(r'^index.html/',views.IndexView.as_view(),name='index'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
#	url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$, views.archives, name='archives'),
	url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
	url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
	url(r'^tag/(?P<pk>[0-9]+)/$',views.tag, name='tag'),
        
]

blog/users/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin

from users import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
     
        ]

blog/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>  知其白，守其黑。 </title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- move device -->
<!--
    <!-- bootstrap css -->
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
-->	
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
	
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">



     <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
	
	
    <link rel="shortcut icon" href="#" />
	
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">  
	
    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	
	
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

                <nav class="navbar navbar-default navbar-fixed-top">
                    <div class="container-fluid">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only"></span>
                        </button>
                    </div>

             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      			<ul class="nav navbar-nav" style="float:none;text-align:center;">
			    <li ><a href="{% url 'blogapp:index' %}"> <b>  <font color = "grey" size = 4 > 知其白，守其黑。</font></b></a> </li>
                            <li class="" style="float:none;display:inline-block;margin:0em;"><a href="{% url 'blogapp:index' %}" data-hover="首页">首页</a></li>
                            <li class="" style="float:none;display:inline-block;margin:0em;"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="" style="float:none;display:inline-block;margin:0em;"><a href="about.html" data-hover="关于">关于</a></li>

		     				    
		<li style="float:right;display:inline-block;margin:0em 0em 1em 3em;">   {% if user.is_authenticated %}
                <a href="#">欢迎你：{{ user.username }}</a>
            {% else %}
              
                    <button  type="button" class="btn btn-default navbar-btn" ><a href="{% url 'login' %}">登录</a></button>
                    <button  type="button" class="btn btn-default navbar-btn" ><a href="{% url 'users:register' %}">注册</a></button>
                
            {% endif %} 
														   </li>
	
		     
  <form class="form-inline navbar-right" >
                <div class="input-group">
                    <span class="input-group-addon">@</span>
                    <input list="dl" type="text" class="form-control" placeholder="Search"/>
                    
                </div>
                            <button type="submit" class="btn btn-successt">搜索</button>
                        </form>
 </ul>	 				
												     
</div>
</nav>	

</div>
<br><br><br>
	
<div class="copyrights">Collect from <a>言念</a></div>
<div class="copyrights">Modified by <a>言念</a></div>

<div class="content-body">
    <div class="container-fluid">
        <div  class="row" >
            <main class="col-md-8">

                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                   {% get_recent_posts as recent_post_list %}
                     <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }} </a>
                        </li>
                         {% empty %} 
                          暂无文章！
                          {% endfor %}
                        
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
			<ul>
			{% for date in date_list %}
                        <li>
			<a href="{% url 'blogapp:archives' date.year date.month %}"> 
				{{ date.year }}年{{ date.month }} 月</a >
                        
			{% empty %}
			暂无归档！
		        {% endfor %}	
			</ul>
			
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
			<ul>
			{% for category in category_list%}
                        <li>
                            <a href="{% url 'blogapp:category' category.pk %}">{{ category.name}}<span class="post-count"></span></a>
                        </li>
			
                        {% empty %}
			暂无分类！
			{% endfor %}
                            
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
			{% get_tags as tags_list %}
                    <ul>
                       {% for tags in tags_list %}
			    <li>
				    <a herf = "{% url 'blogapp:tag' tags.pk %}">{{tags.name}}<span class="post-count"></span></a>              
				</li>	
			    {% empty %}
			暂无标签！
			{% endfor %}
			</ul>
                </div>
		    
		    
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
	
<br><br>
<nav aria-label="...">	
	<ul class="pager">
<!--
       <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
-->
{% if is_paginated %}
<!--<div class="pagination justify-content-center" style="text-align:center;font-size=5;">-->
  {% if first %}
<li>	
    <a href="?page=1" >1</a>
	</li>
	{% endif %}
  {% if left %}
    {% if left_has_more %}
        <li >...</li>
    {% endif %}
    {% for i in left %}
	<li>
        <a href="?page={{ i }}">{{ i }}</a>
	</li>
		{% endfor %}
  {% endif %}
	<li>
  <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
  </li>
		{% if right %}
    {% for i in right %}
      <li>  <a href="?page={{ i }}">{{ i }}</a>
    </li>
	      {% endfor %}
    {% if right_has_more %}
        <li>...</li>
    {% endif %}
  {% endif %}
  {% if last %}
	<li>
    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
  </li>
		{% endif %}
<!--</div>-->
{% endif %}
<!--
	
	<li>
      <a href="?page={{ page_obj.number }}+{{1}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
-->
		</ul>
</nav>
<br><br>



	
	
	
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018<a>言念</a>
                   
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>



</body>
</html>